# NER Logistics — operational entry points.
#
# `make` on its own lists the targets. Two paths are supported:
#
#   Docker      make setup && make up && make migrate && make seed
#   Native      make venv && make install && make migrate && make seed && make dev-api
#
# The native path exists because Docker is not installed everywhere, and a
# hackathon demo should not hinge on it. It needs PostgreSQL 16 with PostGIS 3.4
# reachable at the POSTGRES_* values in .env.
#
# On Windows, run these from Git Bash or WSL. Every recipe is a single readable
# command, so if make is unavailable the underlying command can be copied out.

SHELL := /bin/bash
.DEFAULT_GOAL := help

COMPOSE ?= docker compose
API_DIR := services/api
WEB_DIR := apps/web
VENV := $(API_DIR)/.venv
PY := $(VENV)/bin/python
PIP := $(VENV)/bin/pip
# Northeast India extract, ~200 MB. Geofabrik publishes it daily.
OSM_URL := https://download.geofabrik.de/asia/india/northeast-latest.osm.pbf
OSM_FILE := data/osm/northeast-india-latest.osm.pbf

.PHONY: help
help:  ## List every target
	@echo "NER Logistics — make targets"
	@echo
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	  | sort \
	  | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'
	@echo
	@echo "Docker path : setup -> up -> migrate -> seed"
	@echo "Native path : venv -> install -> migrate -> seed -> dev-api"

# ------------------------------------------------------------------- bootstrap

.PHONY: setup
setup: .env  ## Create .env from the template with a generated SECRET_KEY
	@echo "ready: review .env, then 'make up' (Docker) or 'make venv' (native)"

.env:
	@cp .env.example .env
	@# A generated key beats the placeholder, which the API refuses outside
	@# development anyway. python is used because sed -i differs across platforms.
	@python3 -c "import pathlib, secrets; \
	p = pathlib.Path('.env'); \
	p.write_text(p.read_text().replace('change-me-in-production', secrets.token_urlsafe(48), 1))"
	@echo "created .env with a generated SECRET_KEY (not committed)"
# ---------------------------------------------------------------------- docker

.PHONY: build
build: .env  ## Build the API image
	$(COMPOSE) build api

.PHONY: up
up: .env  ## Start postgres, redis and the API (detached)
	$(COMPOSE) up -d postgres redis api
	@echo "API on http://localhost:8000  docs at /docs"

.PHONY: down
down:  ## Stop the stack, keeping data volumes
	$(COMPOSE) down

.PHONY: ps
ps:  ## Show container status and health
	$(COMPOSE) ps

.PHONY: logs
logs:  ## Follow API logs (make logs SERVICE=postgres for another)
	$(COMPOSE) logs -f $(or $(SERVICE),api)

.PHONY: restart
restart:  ## Restart the API container
	$(COMPOSE) restart api

.PHONY: db-shell
db-shell:  ## psql inside the postgres container
	$(COMPOSE) exec postgres psql -U $${POSTGRES_USER:-ner} -d $${POSTGRES_DB:-ner_logistics}

.PHONY: redis-shell
redis-shell:  ## redis-cli inside the redis container
	$(COMPOSE) exec redis redis-cli

.PHONY: api-shell
api-shell:  ## bash inside the API container
	$(COMPOSE) exec api bash

# ----------------------------------------------------------------------- native

.PHONY: venv
venv: $(VENV)  ## Create the API virtualenv
$(VENV):
	python3 -m venv $(VENV)
	$(PIP) install --upgrade pip
	@echo "created $(VENV) — now run 'make install'"

.PHONY: install
install: $(VENV)  ## Install API runtime and dev dependencies
	$(PIP) install -r $(API_DIR)/requirements.txt -r $(API_DIR)/requirements-dev.txt

.PHONY: dev-api
dev-api:  ## Run the API natively with reload
	cd $(API_DIR) && .venv/bin/uvicorn app.main:app --reload --port 8000

.PHONY: dev-web
dev-web:  ## Run the Next.js dev server (Phase 2 onward)
	cd $(WEB_DIR) && npm run dev
# -------------------------------------------------------------------- database
# Each target runs in the container when the API container is up, and in the
# virtualenv otherwise, so the same command works on both paths.

define run_api
	@if $(COMPOSE) ps --status running --services 2>/dev/null | grep -qx api; then \
	  echo "-> in container"; $(COMPOSE) exec -T api $(1); \
	else \
	  echo "-> in $(VENV)"; cd $(API_DIR) && .venv/bin/$(1); \
	fi
endef

.PHONY: migrate
migrate:  ## Apply all migrations (alembic upgrade head)
	$(call run_api,alembic upgrade head)

.PHONY: migrate-down
migrate-down:  ## Roll back one revision
	$(call run_api,alembic downgrade -1)

.PHONY: migration-status
migration-status:  ## Show the current revision
	$(call run_api,alembic current -v)

.PHONY: revision
revision:  ## New autogenerated revision: make revision M="add x"
	@test -n "$(M)" || { echo "usage: make revision M=\"message\""; exit 1; }
	$(call run_api,alembic revision --autogenerate -m "$(M)")

.PHONY: seed
seed:  ## Apply reference data (idempotent)
	$(call run_api,python scripts/seed.py)

.PHONY: seed-dry
seed-dry:  ## Report what seeding would change, write nothing
	$(call run_api,python scripts/seed.py --dry-run --verbose)

.PHONY: bootstrap
bootstrap: up migrate seed  ## Docker: start, migrate and seed in one step

# -------------------------------------------------------------- quality gates

.PHONY: test
test:  ## Run the API test suite
	$(call run_api,pytest -q)

.PHONY: test-cov
test-cov:  ## Run tests with a coverage report
	$(call run_api,pytest --cov=app --cov-report=term-missing)

.PHONY: lint
lint:  ## Ruff check
	$(call run_api,ruff check app scripts alembic tests)

.PHONY: format
format:  ## Ruff format in place
	$(call run_api,ruff format app scripts alembic tests)

.PHONY: typecheck
typecheck:  ## mypy on the API package
	$(call run_api,mypy app)

.PHONY: verify
verify:  ## Phase 1 verification: env parity, schema drift, seed invariants
	$(call run_api,python scripts/verify_phase1.py)

.PHONY: check
check: lint typecheck test  ## Everything a commit should pass
# ------------------------------------------------------------------ map data
# Routing runs against OSRM, which needs a prepared graph. This is a download
# and three CPU-bound passes, not something to do during a demo.

.PHONY: osm-download
osm-download: $(OSM_FILE)  ## Fetch the Northeast India OSM extract (~200 MB)
$(OSM_FILE):
	@mkdir -p data/osm
	@echo "downloading $(OSM_URL)"
	curl -L --fail --progress-bar -o $(OSM_FILE) $(OSM_URL)
	@echo "saved $(OSM_FILE) — data/osm is gitignored"

.PHONY: osrm-prepare
osrm-prepare: $(OSM_FILE)  ## Build the OSRM graph (extract, partition, customize)
	@# The car profile ships inside the OSRM image. MLD must match the
	@# --algorithm mld in docker-compose, or osrm-routed refuses to start.
	docker run --rm -v "$(PWD)/data/osm:/data" \
	  ghcr.io/project-osrm/osrm-backend:v5.27.1 \
	  osrm-extract -p /opt/car.lua /data/$(notdir $(OSM_FILE))
	docker run --rm -v "$(PWD)/data/osm:/data" \
	  ghcr.io/project-osrm/osrm-backend:v5.27.1 \
	  osrm-partition /data/northeast-india-latest.osrm
	docker run --rm -v "$(PWD)/data/osm:/data" \
	  ghcr.io/project-osrm/osrm-backend:v5.27.1 \
	  osrm-customize /data/northeast-india-latest.osrm
	@echo "graph ready — 'docker compose --profile routing up -d osrm'"

.PHONY: routing-up
routing-up:  ## Start OSRM (needs osrm-prepare first)
	$(COMPOSE) --profile routing up -d osrm

.PHONY: web-up
web-up:  ## Start the web container (Phase 2 onward)
	$(COMPOSE) --profile web up -d web

# ---------------------------------------------------------------------- cleanup

.PHONY: clean
clean:  ## Remove caches and build artefacts (keeps data and volumes)
	find . -type d -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name .pytest_cache -prune -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name .ruff_cache -prune -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name .mypy_cache -prune -exec rm -rf {} + 2>/dev/null || true
	rm -rf $(WEB_DIR)/.next coverage htmlcov .coverage
	@echo "caches removed"

.PHONY: reset-db
reset-db:  ## DESTRUCTIVE: drop and recreate the schema, then reseed
	@# Guarded because it deletes every incident, shipment and audit row.
	@test "$(CONFIRM)" = "yes" || { \
	  echo "This drops all data in $${POSTGRES_DB:-ner_logistics}."; \
	  echo "Re-run: make reset-db CONFIRM=yes"; exit 1; }
	$(call run_api,alembic downgrade base)
	$(call run_api,alembic upgrade head)
	$(call run_api,python scripts/seed.py)

.PHONY: nuke
nuke:  ## DESTRUCTIVE: remove containers and volumes (all data lost)
	@test "$(CONFIRM)" = "yes" || { \
	  echo "This removes the postgres and redis volumes permanently."; \
	  echo "Re-run: make nuke CONFIRM=yes"; exit 1; }
	$(COMPOSE) down -v --remove-orphans
