"""Routes, the candidates they were chosen from, and their event timeline.

Three tables because the product promise is a comparison, not an answer:

``route_candidates``  every alternative that was generated and scored, kept with
                      its full score breakdown and the reason it was or was not
                      recommended. This is what the comparison view renders and
                      what makes a recommendation auditable after the fact.
``routes``            the alternative that was actually committed to a shipment.
``route_events``      what happened to it afterwards — risk rose, a segment was
                      blocked, it was rerouted, an officer overrode it.

Segment membership is stored as a ``UUID[]`` with a GIN index rather than a join
table, because the query that matters most in the demo — "which shipments use
this segment that just closed?" — becomes a single indexed ``= ANY(segment_ids)``
lookup.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Any, List, Optional

import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.enums import RiskLevel, RouteEventType, RouteStatus
from app.db.base import (
    Base,
    ConfidenceMixin,
    ProvenanceMixin,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
    pg_enum,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from app.models.shipment import Shipment

class RouteCandidate(
    UUIDPrimaryKeyMixin, TimestampMixin, ProvenanceMixin, ConfidenceMixin, Base
):
    """One scored alternative produced by a single planning request.

    Candidates are never deleted when a route is chosen. Keeping the rejected
    alternatives with their scores is the difference between "the system picked
    this" and "the system picked this instead of those, for these reasons".
    """

    __tablename__ = "route_candidates"
    __table_args__ = (
        sa.UniqueConstraint("request_id", "label", name="uq_route_candidates_label"),
        sa.Index("ix_route_candidates_request_rank", "request_id", "rank"),
        sa.Index("ix_route_candidates_segments", "segment_ids", postgresql_using="gin"),
        sa.CheckConstraint("distance_km >= 0", name="candidate_distance_non_negative"),
        sa.CheckConstraint(
            "risk_score >= 0 AND risk_score <= 100", name="candidate_risk_range"
        ),
        sa.CheckConstraint(
            "reliability_score >= 0 AND reliability_score <= 100",
            name="candidate_reliability_range",
        ),
    )

    #: Groups every candidate generated by one call to the routing engine, so the
    #: comparison view can fetch a coherent set even after later replanning.
    request_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    shipment_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("shipments.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    #: Stable human label used in the UI and in explanations: ``ROUTE A``.
    label: Mapped[str] = mapped_column(sa.String(40), nullable=False)
    #: 1 is the best-scoring candidate.
    rank: Mapped[int] = mapped_column(sa.SmallInteger, nullable=False, default=1)

    # ------------------------------------------------------------------ geometry
    geom: Mapped[Any] = mapped_column(
        Geometry(geometry_type="LINESTRING", srid=4326, spatial_index=True),
        nullable=False,
    )
    #: Ordered segment identifiers. GIN-indexed so "which candidates cross this
    #: segment" is a single lookup when a closure arrives.
    segment_ids: Mapped[List[uuid.UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, server_default=sa.text("'{}'")
    )
    waypoint_names: Mapped[Optional[List[str]]] = mapped_column(
        ARRAY(sa.String(200)), nullable=True
    )

    # ------------------------------------------------------- objective components
    distance_km: Mapped[float] = mapped_column(sa.Float, nullable=False)
    #: Travel time after weather, incident and road-condition penalties.
    duration_minutes: Mapped[float] = mapped_column(sa.Float, nullable=False)
    #: Free-flow time before penalties, so the delay attribution is visible.
    base_duration_minutes: Mapped[Optional[float]] = mapped_column(
        sa.Float, nullable=True
    )
    predicted_eta: Mapped[Optional[datetime]] = mapped_column(
        sa.TIMESTAMP(timezone=True), nullable=True
    )
    #: Worst segment risk along the path, 0-100.
    risk_score: Mapped[float] = mapped_column(sa.Float, nullable=False, default=0.0)
    risk_level: Mapped[RiskLevel] = mapped_column(
        pg_enum(RiskLevel, "risk_level"), nullable=False, default=RiskLevel.LOW
    )
    #: Probability-derived expectation that the corridor stays usable for the whole
    #: journey, 0-100. This is the term the NORMAL profile weights most heavily.
    reliability_score: Mapped[float] = mapped_column(
        sa.Float, nullable=False, default=0.0
    )
    estimated_cost: Mapped[Optional[float]] = mapped_column(sa.Float, nullable=True)
    estimated_fuel_litres: Mapped[Optional[float]] = mapped_column(
        sa.Float, nullable=True
    )

    # ------------------------------------------------------------ admissibility
    #: False when any segment rejects the vehicle envelope. An inadmissible
    #: candidate is kept for the comparison view but can never be recommended.
    is_vehicle_compatible: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=True
    )
    #: Which limit failed, e.g. "bridge on NH-37 segment 12 limits 18t, vehicle 24t".
    incompatibility_reason: Mapped[Optional[str]] = mapped_column(
        sa.Text, nullable=True
    )
    blocked_segment_count: Mapped[int] = mapped_column(
        sa.SmallInteger, nullable=False, default=0
    )

    # -------------------------------------------------------------- explanation
    #: Weighted total the ranking used, lower is better.
    score_total: Mapped[Optional[float]] = mapped_column(sa.Float, nullable=True)
    #: Per-objective contributions keyed by objective name, e.g.
    #: ``{"reliability": 0.40, "eta": 0.25, ...}`` alongside the normalised term
    #: values, so the UI can show how the total was reached.
    score_breakdown: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB, nullable=True
    )
    #: Which weight profile produced this score. Policy lives in configuration.
    weight_profile_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("routing_weight_profiles.id", ondelete="SET NULL"),
        nullable=True,
    )
    #: Ordered risk drivers, highest contribution first, for the "because" text.
    top_risk_factors: Mapped[Optional[list[dict[str, Any]]]] = mapped_column(
        JSONB, nullable=True
    )
    is_recommended: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=False
    )
    #: Full sentence shown to the operator. Never "the AI chose this".
    recommendation_reason: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    #: Why this alternative lost, when it did.
    rejection_reason: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)

    # ------------------------------------------------------------- traceability
    #: Which routing backend produced the geometry (``osrm``, ``internal_graph``).
    #: Recorded per candidate so a provider swap is visible in old records.
    routing_provider: Mapped[Optional[str]] = mapped_column(sa.String(40), nullable=True)
    engine_version: Mapped[Optional[str]] = mapped_column(sa.String(40), nullable=True)
    #: Oldest observation feeding this score. The UI shows it as data freshness,
    #: because a confident number from stale inputs is not trustworthy.
    oldest_input_observed_at: Mapped[Optional[datetime]] = mapped_column(
        sa.TIMESTAMP(timezone=True), nullable=True
    )
    #: Set when generated inside a what-if run; excluded from analytics.
    simulation_run_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), nullable=True, index=True
    )

    @property
    def is_admissible(self) -> bool:
        """Whether this candidate may be recommended at all.

        A candidate is inadmissible if the vehicle cannot physically or legally
        use one of its segments, or if any segment is currently blocked. Both are
        hard constraints, so no weighting can rescue such a route.
        """

        return self.is_vehicle_compatible and self.blocked_segment_count == 0


class Route(
    UUIDPrimaryKeyMixin, TimestampMixin, ProvenanceMixin, ConfidenceMixin, Base
):
    """The alternative that was committed to a shipment.

    A reroute does not mutate this row: the old route becomes ``SUPERSEDED`` and
    points at its replacement, so the corridor history of a consignment survives.
    """

    __tablename__ = "routes"
    __table_args__ = (
        sa.Index("ix_routes_shipment_status", "shipment_id", "status"),
        sa.Index("ix_routes_segments", "segment_ids", postgresql_using="gin"),
        sa.CheckConstraint("distance_km >= 0", name="route_distance_non_negative"),
        sa.CheckConstraint(
            "risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)",
            name="route_risk_range",
        ),
    )

    shipment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("shipments.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    #: The scored alternative this route was materialised from, preserving the
    #: comparison that justified it.
    candidate_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("route_candidates.id", ondelete="SET NULL"),
        nullable=True,
    )
    status: Mapped[RouteStatus] = mapped_column(
        pg_enum(RouteStatus, "route_status"),
        nullable=False,
        default=RouteStatus.PROPOSED,
        index=True,
    )
    #: Increments on every reroute of the same shipment, starting at 1.
    version: Mapped[int] = mapped_column(sa.SmallInteger, nullable=False, default=1)

    geom: Mapped[Any] = mapped_column(
        Geometry(geometry_type="LINESTRING", srid=4326, spatial_index=True),
        nullable=False,
    )
    segment_ids: Mapped[List[uuid.UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, server_default=sa.text("'{}'")
    )

    distance_km: Mapped[float] = mapped_column(sa.Float, nullable=False)
    duration_minutes: Mapped[float] = mapped_column(sa.Float, nullable=False)
    base_duration_minutes: Mapped[Optional[float]] = mapped_column(
        sa.Float, nullable=True
    )
    risk_score: Mapped[Optional[float]] = mapped_column(sa.Float, nullable=True)
    risk_level: Mapped[Optional[RiskLevel]] = mapped_column(
        pg_enum(RiskLevel, "risk_level"), nullable=True
    )
    reliability_score: Mapped[Optional[float]] = mapped_column(sa.Float, nullable=True)
    estimated_cost: Mapped[Optional[float]] = mapped_column(sa.Float, nullable=True)

    # ---------------------------------------------------------------- lifecycle
    activated_at: Mapped[Optional[datetime]] = mapped_column(
        sa.TIMESTAMP(timezone=True), nullable=True
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        sa.TIMESTAMP(timezone=True), nullable=True
    )
    #: Replacement route after a reroute. Self-referential, so the chain of
    #: corridors a shipment actually used can be walked in order.
    superseded_by_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), sa.ForeignKey("routes.id", ondelete="SET NULL"), nullable=True
    )
    superseded_at: Mapped[Optional[datetime]] = mapped_column(
        sa.TIMESTAMP(timezone=True), nullable=True
    )

    # --------------------------------------------------------- human authority
    selected_by_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    #: True when an officer committed a route the engine did not recommend. The
    #: override is permitted — humans hold the authority — but it is recorded,
    #: audit-logged and shown in the timeline.
    is_manual_override: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, default=False
    )
    override_reason: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    #: Copied from the candidate so the justification survives even if planning
    #: inputs are later pruned.
    recommendation_reason: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    weight_profile_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("routing_weight_profiles.id", ondelete="SET NULL"),
        nullable=True,
    )
    attributes: Mapped[Optional[dict[str, Any]]] = mapped_column(JSONB, nullable=True)

    shipment: Mapped["Shipment"] = relationship(
        "Shipment",
        back_populates="routes",
        foreign_keys=[shipment_id],
    )
    candidate: Mapped[Optional["RouteCandidate"]] = relationship("RouteCandidate")
    events: Mapped[List["RouteEvent"]] = relationship(
        back_populates="route",
        cascade="all, delete-orphan",
        order_by="RouteEvent.occurred_at",
    )

    @property
    def is_live(self) -> bool:
        """Whether this route currently governs the shipment."""

        return self.status == RouteStatus.ACTIVE


class RouteEvent(UUIDPrimaryKeyMixin, ProvenanceMixin, Base):
    """One thing that happened to a route.

    This is the narrative the command centre replays during a demo and the
    evidence a reviewer reads afterwards: risk rose at 04:10, the segment was
    blocked at 04:12, the shipment was rerouted at 04:13. It is append-only, so
    it omits ``TimestampMixin`` — ``occurred_at`` is the only time that matters.
    """

    __tablename__ = "route_events"
    __table_args__ = (
        sa.Index("ix_route_events_route_time", "route_id", "occurred_at"),
        sa.Index("ix_route_events_type_time", "event_type", "occurred_at"),
    )

    route_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("routes.id", ondelete="CASCADE"),
        nullable=False,
    )
    #: Denormalised so a shipment timeline spanning several reroutes is one query.
    shipment_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("shipments.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    event_type: Mapped[RouteEventType] = mapped_column(
        pg_enum(RouteEventType, "route_event_type"), nullable=False
    )
    occurred_at: Mapped[datetime] = mapped_column(
        sa.TIMESTAMP(timezone=True), nullable=False
    )
    #: Operator-readable sentence, already resolved to concrete places and values.
    description: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)

    # ------------------------------------------------------------------- causality
    #: What triggered the event, when it was a stored object: the incident that
    #: closed the road, or the segment whose risk changed.
    triggered_by_incident_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("incidents.id", ondelete="SET NULL"),
        nullable=True,
    )
    triggered_by_segment_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("road_segments.id", ondelete="SET NULL"),
        nullable=True,
    )
    #: Null for engine-generated events; set when a person acted.
    actor_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )

    # --------------------------------------------------------------- measurements
    previous_risk_score: Mapped[Optional[float]] = mapped_column(sa.Float, nullable=True)
    new_risk_score: Mapped[Optional[float]] = mapped_column(sa.Float, nullable=True)
    previous_eta: Mapped[Optional[datetime]] = mapped_column(
        sa.TIMESTAMP(timezone=True), nullable=True
    )
    new_eta: Mapped[Optional[datetime]] = mapped_column(
        sa.TIMESTAMP(timezone=True), nullable=True
    )
    #: Anything the event type needs that does not deserve a column.
    payload: Mapped[Optional[dict[str, Any]]] = mapped_column(JSONB, nullable=True)

    route: Mapped["Route"] = relationship(back_populates="events")

