"""OpenStreetMap road linework.

OSM is the only openly licensed road network with usable coverage of the North
Eastern Region, and it is real data — surveyed and maintained by people, not
generated by us. So records from this module carry ``REAL`` provenance. Two
obligations come with that. The licence is ODbL: any published map or derived
database has to attribute OpenStreetMap contributors, which is a legal
requirement for a government-facing product and not a nicety. And the coverage is
uneven — trunk routes are well mapped, rural link roads in the hills often carry
no surface, width or weight tags at all. Absent tags are represented as ``None``,
never as a guessed value, because a guess here silently becomes a vehicle
restriction decision later.

That is also why this module does not fill in ``free_flow_speed_kmph`` from the
road class. A record labelled ``REAL`` must not contain a number we invented; the
Phase 2 pipeline applies speed defaults itself, where the assumption can be
recorded as ``DERIVED`` alongside the slope and terrain it is based on. Only an
explicit ``maxspeed`` tag becomes a speed here.

Two sources, for two different jobs. :class:`LocalExtractOSMProvider` reads a
prepared regional extract and is what bulk ingestion uses.
:class:`OverpassOSMProvider` answers small ad-hoc queries against the public API
and must not be used for bulk work — it is a shared volunteer service.
"""

from __future__ import annotations

import abc
import asyncio
import json
import math
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, ClassVar, Dict, Iterable, List, Optional, Sequence, Tuple

from app.core.enums import DataProvenance, RoadType, SurfaceType
from app.providers.base import (
    Provider,
    ProviderResponseError,
    ProviderStatus,
    ProviderUnavailable,
)
from app.providers.models import RoadFeatureRecord

__all__ = [
    "ROUTABLE_HIGHWAY_VALUES",
    "LocalExtractOSMProvider",
    "OSMProvider",
    "OverpassOSMProvider",
    "parse_lanes",
    "parse_measure",
    "parse_speed_kmph",
    "road_type_from_tags",
    "surface_from_tags",
]

#: ``highway`` values we treat as part of the freight-capable network. Footways,
#: cycleways and steps are excluded: a relief truck cannot use them, and letting
#: them into the graph produces routes that look shorter and are not drivable.
ROUTABLE_HIGHWAY_VALUES: Tuple[str, ...] = (
    "motorway", "motorway_link", "trunk", "trunk_link",
    "primary", "primary_link", "secondary", "secondary_link",
    "tertiary", "tertiary_link", "unclassified", "residential",
    "living_street", "service", "track", "road",
)

_HIGHWAY_TO_ROAD_TYPE: Dict[str, RoadType] = {
    "motorway": RoadType.NATIONAL_HIGHWAY,
    "motorway_link": RoadType.NATIONAL_HIGHWAY,
    "trunk": RoadType.NATIONAL_HIGHWAY,
    "trunk_link": RoadType.NATIONAL_HIGHWAY,
    "primary": RoadType.STATE_HIGHWAY,
    "primary_link": RoadType.STATE_HIGHWAY,
    "secondary": RoadType.DISTRICT_ROAD,
    "secondary_link": RoadType.DISTRICT_ROAD,
    "tertiary": RoadType.RURAL_ROAD,
    "tertiary_link": RoadType.RURAL_ROAD,
    "unclassified": RoadType.RURAL_ROAD,
    "road": RoadType.OTHER,
    "residential": RoadType.URBAN_ROAD,
    "living_street": RoadType.URBAN_ROAD,
    "service": RoadType.URBAN_ROAD,
    "track": RoadType.TRACK,
}

_SURFACE_MAP: Dict[str, SurfaceType] = {
    "asphalt": SurfaceType.ASPHALT,
    "chipseal": SurfaceType.ASPHALT,
    "concrete": SurfaceType.CONCRETE,
    "concrete:plates": SurfaceType.CONCRETE,
    "concrete:lanes": SurfaceType.CONCRETE,
    "paved": SurfaceType.PAVED_OTHER,
    "paving_stones": SurfaceType.PAVED_OTHER,
    "sett": SurfaceType.PAVED_OTHER,
    "cobblestone": SurfaceType.PAVED_OTHER,
    "metal": SurfaceType.PAVED_OTHER,
    "wood": SurfaceType.PAVED_OTHER,
    "gravel": SurfaceType.GRAVEL,
    "fine_gravel": SurfaceType.GRAVEL,
    "compacted": SurfaceType.GRAVEL,
    "pebblestone": SurfaceType.GRAVEL,
    "rock": SurfaceType.GRAVEL,
    "stone": SurfaceType.GRAVEL,
    "dirt": SurfaceType.EARTH,
    "earth": SurfaceType.EARTH,
    "ground": SurfaceType.EARTH,
    "mud": SurfaceType.EARTH,
    "sand": SurfaceType.EARTH,
    "clay": SurfaceType.EARTH,
    "grass": SurfaceType.EARTH,
    "unpaved": SurfaceType.UNPAVED_OTHER,
}

#: ``ref`` prefixes are a better signal of administrative class than ``highway``
#: in India: a National Highway through a small town is often tagged
#: ``highway=primary`` locally while still carrying an ``NH`` reference. MDR and
#: ODR are the Major/Other District Road designations used by state PWDs.
_REF_PREFIX_TO_ROAD_TYPE: Tuple[Tuple[str, RoadType], ...] = (
    ("NH", RoadType.NATIONAL_HIGHWAY),
    ("AH", RoadType.NATIONAL_HIGHWAY),  # Asian Highway; AH1/AH2 run through the NER
    ("NE", RoadType.NATIONAL_HIGHWAY),  # National Expressway
    ("SH", RoadType.STATE_HIGHWAY),
    ("MDR", RoadType.DISTRICT_ROAD),
    ("ODR", RoadType.DISTRICT_ROAD),
)

_TRUTHY = frozenset({"yes", "true", "1"})
_NUMBER = re.compile(r"-?\d+(?:\.\d+)?")
_FEET_INCHES = re.compile(r"^\s*(\d+(?:\.\d+)?)\s*'\s*(?:(\d+(?:\.\d+)?)\s*\")?\s*$")


def road_type_from_tags(tags: Dict[str, str]) -> RoadType:
    """Functional class of a way, ``ref`` taking precedence over ``highway``.

    Bridges and tunnels keep their functional class — a National Highway bridge
    is still a National Highway, and ``is_bridge`` / ``is_tunnel`` carry the
    structure separately. :attr:`RoadType.BRIDGE` and :attr:`RoadType.TUNNEL`
    exist for standalone structures whose class is genuinely unknown, and are not
    assigned here.
    """

    ref = (tags.get("ref") or tags.get("nat_ref") or "").strip().upper()
    if ref:
        # A way may carry several refs ("NH27;SH13"); the highest class wins.
        for prefix, road_type in _REF_PREFIX_TO_ROAD_TYPE:
            if re.search(rf"(?:^|[;,\s]){prefix}[\s\-]?\d", ref):
                return road_type
    highway = (tags.get("highway") or "").strip().lower()
    return _HIGHWAY_TO_ROAD_TYPE.get(highway, RoadType.OTHER)


def surface_from_tags(tags: Dict[str, str]) -> SurfaceType:
    """``surface`` mapped to our coarser classes, ``UNKNOWN`` when untagged.

    ``UNKNOWN`` is common in this region and is deliberately not treated as
    "paved". The risk engine penalises unknown surfaces mildly rather than
    assuming the optimistic case.
    """

    raw = (tags.get("surface") or "").strip().lower()
    if not raw:
        smoothness = (tags.get("smoothness") or "").strip().lower()
        if smoothness in {"excellent", "good"}:
            return SurfaceType.PAVED_OTHER
        if smoothness in {"very_bad", "horrible", "very_horrible", "impassable"}:
            return SurfaceType.UNPAVED_OTHER
        return SurfaceType.UNKNOWN
    return _SURFACE_MAP.get(raw.split(";")[0], SurfaceType.UNKNOWN)


def parse_measure(raw: Optional[str], *, kind: str) -> Optional[float]:
    """Parse an OSM dimension tag into tonnes (weight) or metres (length).

    OSM units are conventional, not enforced: ``maxweight=3.5`` means tonnes,
    ``maxheight=12'6"`` means feet and inches, and ``maxwidth=250 cm`` happens.
    Returns ``None`` for anything unparseable rather than a default, because a
    default here becomes a wrong answer to "can this truck use this bridge".
    """

    if raw is None:
        return None
    text = raw.strip().lower()
    if not text or text in {"none", "unknown", "default", "no"}:
        return None

    if kind == "length":
        match = _FEET_INCHES.match(text)
        if match:
            feet = float(match.group(1))
            inches = float(match.group(2) or 0.0)
            return round((feet * 12.0 + inches) * 0.0254, 3)

    number = _NUMBER.search(text)
    if number is None:
        return None
    value = float(number.group())
    unit = text[number.end():].strip().replace(".", "")

    if kind == "weight":
        if unit in {"kg", "kgs", "kilogram", "kilograms"}:
            value /= 1000.0
        elif unit in {"lb", "lbs", "pound", "pounds"}:
            value *= 0.000453592
        # "", "t", "tonne", "tonnes", "ton", "mt" are already tonnes.
    elif kind == "length":
        if unit in {"cm"}:
            value /= 100.0
        elif unit in {"mm"}:
            value /= 1000.0
        elif unit in {"ft", "feet", "foot"}:
            value *= 0.3048
        elif unit in {"in", "inch", "inches"}:
            value *= 0.0254
        elif unit in {"km"}:
            value *= 1000.0
    if value <= 0:
        return None
    return round(value, 3)


def parse_speed_kmph(raw: Optional[str]) -> Optional[float]:
    """Parse ``maxspeed``. Only an explicit tag yields a speed — never a default."""

    if raw is None:
        return None
    text = raw.strip().lower()
    number = _NUMBER.search(text)
    if number is None:
        return None
    value = float(number.group())
    if "mph" in text:
        value *= 1.609344
    elif "knot" in text:
        value *= 1.852
    if value <= 0 or value > 200:
        return None
    return round(value, 1)


def parse_lanes(raw: Optional[str]) -> Optional[int]:
    """Lane count, ignoring the ``lanes=1;2`` and ``lanes=2.5`` oddities."""

    if raw is None:
        return None
    number = _NUMBER.search(raw)
    if number is None:
        return None
    try:
        lanes = int(float(number.group()))
    except ValueError:
        return None
    return lanes if 1 <= lanes <= 12 else None


def _linestrings(geometry: Dict[str, Any]) -> List[List[List[float]]]:
    """Coordinate rings of a Line or MultiLineString; ``[]`` for anything else.

    Polygons are dropped rather than converted. An OSM way tagged both
    ``highway`` and ``area`` is a pedestrian plaza or a car park, not a corridor.
    """

    kind = geometry.get("type")
    coords = geometry.get("coordinates")
    if kind == "LineString" and isinstance(coords, list):
        return [coords]
    if kind == "MultiLineString" and isinstance(coords, list):
        return [part for part in coords if isinstance(part, list)]
    return []


def _bounds(
    rings: Sequence[Sequence[Sequence[float]]],
) -> Optional[Tuple[float, float, float, float]]:
    """(min_lon, min_lat, max_lon, max_lat) over lon/lat pairs, or ``None``."""

    lons: List[float] = []
    lats: List[float] = []
    for ring in rings:
        for point in ring:
            if len(point) < 2:
                continue
            lon, lat = float(point[0]), float(point[1])
            if math.isfinite(lon) and math.isfinite(lat):
                lons.append(lon)
                lats.append(lat)
    if not lons:
        return None
    return (min(lons), min(lats), max(lons), max(lats))


def _overlaps(a: Tuple[float, float, float, float], b: Tuple[float, float, float, float]) -> bool:
    return not (a[2] < b[0] or a[0] > b[2] or a[3] < b[1] or a[1] > b[3])


def _way_id(feature: Dict[str, Any], properties: Dict[str, Any]) -> Optional[int]:
    """Recover the OSM way id from the several shapes exporters produce.

    ``osmium export`` writes ``@id``, ``ogr2ogr`` writes ``osm_id``, hand-made
    files use ``osm_way_id``, and some write ``way/12345``. Losing this id would
    break de-duplication on re-ingest, so all four are accepted.
    """

    for key in ("osm_way_id", "@id", "osm_id", "id"):
        raw = properties.get(key, feature.get(key) if key == "id" else None)
        if raw is None:
            continue
        if isinstance(raw, int):
            return raw
        text = str(raw)
        if text.startswith("way/"):
            text = text[4:]
        elif "/" in text:
            continue  # node/… or relation/… is not a way id
        try:
            return int(text)
        except ValueError:
            continue
    return None


def _record_from_tags(
    *,
    way_id: Optional[int],
    geometry: Dict[str, Any],
    tags: Dict[str, str],
    provenance: DataProvenance,
    source: str,
    observed_at: datetime,
) -> RoadFeatureRecord:
    """Build one record. The only place OSM tag semantics are interpreted."""

    return RoadFeatureRecord(
        provenance=provenance,
        source=source,
        observed_at=observed_at,
        osm_way_id=way_id,
        geometry=geometry,
        name=tags.get("name") or tags.get("name:en") or None,
        ref=tags.get("ref") or tags.get("nat_ref") or None,
        road_type=road_type_from_tags(tags),
        surface=surface_from_tags(tags),
        lanes=parse_lanes(tags.get("lanes")),
        width_m=parse_measure(tags.get("width"), kind="length"),
        is_bridge=(tags.get("bridge") or "no").lower() not in {"no", ""},
        is_tunnel=(tags.get("tunnel") or "no").lower() not in {"no", ""},
        is_oneway=(tags.get("oneway") or "no").lower() in _TRUTHY,
        max_weight_tonnes=parse_measure(
            tags.get("maxweight") or tags.get("maxweightrating"), kind="weight"
        ),
        max_height_m=parse_measure(tags.get("maxheight"), kind="length"),
        max_width_m=parse_measure(tags.get("maxwidth"), kind="length"),
        free_flow_speed_kmph=parse_speed_kmph(tags.get("maxspeed")),
        tags={str(k): str(v) for k, v in tags.items()} or None,
    )


class OSMProvider(Provider):
    """Road linework for an area of interest."""

    kind: ClassVar[str] = "osm"
    provenance: ClassVar[DataProvenance] = DataProvenance.REAL
    #: ODbL requires attribution wherever this data or anything derived from it
    #: is published. Carried on the class so the UI can render it from the
    #: provider report rather than hardcoding a string in a component.
    attribution: ClassVar[str] = "© OpenStreetMap contributors (ODbL 1.0)"

    @abc.abstractmethod
    async def roads(
        self,
        *,
        bbox: Tuple[float, float, float, float],
        road_types: Optional[Iterable[RoadType]] = None,
    ) -> List[RoadFeatureRecord]:
        """Ways overlapping ``bbox`` (min_lon, min_lat, max_lon, max_lat).

        A bbox is required, not optional: "give me every road in the region" is a
        multi-gigabyte answer and the caller should have to say so explicitly by
        passing the region's own bounds.
        """


class LocalExtractOSMProvider(OSMProvider):
    """Reads a prepared regional extract from disk. The bulk ingestion path.

    The configured path normally points at a ``.osm.pbf`` — that is what
    Geofabrik distributes. This adapter does not parse PBF: that needs libosmium,
    a compiled dependency this service does not carry, and doing it inside a web
    process would be the wrong place regardless. Instead the extract is converted
    once by ``scripts/prepare_osm.sh`` and this adapter reads the resulting
    GeoJSON, which it looks for beside the extract as ``<name>.roads.geojson``.

    When that file is missing the error names the exact path and the command that
    produces it, because "provider unavailable" with no further detail is the
    kind of message that costs an hour during setup. Line-delimited GeoJSON
    (``.geojsonl``) is also accepted, which is what ``osmium export -f geojsonseq``
    emits and what makes a large extract streamable.
    """

    implementation: ClassVar[str] = "local_extract"
    source_name: ClassVar[str] = "openstreetmap-extract"
    _GEOJSON_SUFFIXES = frozenset({".geojson", ".json"})
    _SEQ_SUFFIXES = frozenset({".geojsonl", ".ndjson", ".geojsonseq"})

    def __init__(self, extract_path: str) -> None:
        self._configured_path = Path(extract_path)

    @property
    def data_path(self) -> Path:
        """The file actually read: the configured path, or its GeoJSON sidecar."""

        suffix = self._configured_path.suffix.lower()
        if suffix in self._GEOJSON_SUFFIXES or suffix in self._SEQ_SUFFIXES:
            return self._configured_path
        # northeast-india-latest.osm.pbf -> northeast-india-latest.roads.geojson
        stem = self._configured_path.name
        for tail in (".osm.pbf", ".pbf", ".osm.bz2", ".osm.xml", ".osm"):
            if stem.lower().endswith(tail):
                stem = stem[: -len(tail)]
                break
        return self._configured_path.with_name(f"{stem}.roads.geojson")

    def _missing(self) -> ProviderUnavailable:
        return ProviderUnavailable(
            f"{self.name}: no road extract at {self.data_path}. Prepare one with "
            f"`scripts/prepare_osm.sh` (osmium tags-filter + export), or set "
            f"OSM_PROVIDER=overpass for small ad-hoc areas."
        )

    def _load(self) -> List[Dict[str, Any]]:
        """Blocking read. Called via :func:`asyncio.to_thread` by :meth:`roads`."""

        path = self.data_path
        if path.suffix.lower() in self._SEQ_SUFFIXES:
            features: List[Dict[str, Any]] = []
            with path.open("r", encoding="utf-8") as handle:
                for line in handle:
                    line = line.strip().lstrip("\x1e")  # RFC 8142 record separator
                    if not line:
                        continue
                    features.append(json.loads(line))
            return features
        with path.open("r", encoding="utf-8") as handle:
            document = json.load(handle)
        if isinstance(document, dict) and isinstance(document.get("features"), list):
            return document["features"]
        raise ProviderResponseError(
            f"{self.name}: {path} is not a GeoJSON FeatureCollection"
        )

    async def roads(
        self,
        *,
        bbox: Tuple[float, float, float, float],
        road_types: Optional[Iterable[RoadType]] = None,
    ) -> List[RoadFeatureRecord]:
        path = self.data_path
        if not path.exists():
            raise self._missing()
        try:
            features = await asyncio.to_thread(self._load)
        except OSError as exc:
            raise ProviderUnavailable(f"{self.name}: cannot read {path}: {exc}") from exc
        except json.JSONDecodeError as exc:
            raise ProviderResponseError(f"{self.name}: malformed GeoJSON in {path}: {exc}") from exc

        wanted = tuple(road_types) if road_types is not None else None
        observed_at = datetime.now(timezone.utc)
        # The extract's own timestamp would be better than "now", but GeoJSON has
        # nowhere to put it; the ingestion script records the extract date.
        out: List[RoadFeatureRecord] = []
        for feature in features:
            if not isinstance(feature, dict):
                continue
            geometry = feature.get("geometry")
            if not isinstance(geometry, dict):
                continue
            rings = _linestrings(geometry)
            if not rings:
                continue
            bounds = _bounds(rings)
            if bounds is None or not _overlaps(bounds, bbox):
                continue
            properties = feature.get("properties")
            properties = properties if isinstance(properties, dict) else {}
            tags = {
                str(k): str(v)
                for k, v in properties.items()
                if v is not None and not str(k).startswith("@")
            }
            if tags.get("highway", "").lower() not in ROUTABLE_HIGHWAY_VALUES:
                continue
            record = _record_from_tags(
                way_id=_way_id(feature, properties),
                geometry=geometry,
                tags=tags,
                provenance=self.provenance,
                source=self.source_name,
                observed_at=observed_at,
            )
            if wanted is not None and record.road_type not in wanted:
                continue
            out.append(record)
        return out

    async def healthcheck(self) -> ProviderStatus:
        path = self.data_path
        if not path.exists():
            return self.describe(healthy=False, detail=f"extract missing: {path}")
        try:
            size_mb = path.stat().st_size / 1_048_576
        except OSError as exc:  # pragma: no cover - unreadable but present
            return self.describe(healthy=False, detail=f"unreadable: {exc}")
        return self.describe(healthy=True, detail=f"{path.name}, {size_mb:.1f} MB")


class OverpassOSMProvider(OSMProvider):
    """Live queries against the public Overpass API. Small areas only.

    Overpass is run by volunteers on donated hardware. Hammering it to build a
    regional graph is both slow and rude, and the public instance will start
    returning 429s partway through — which in a demo looks like our bug. So this
    adapter refuses a bounding box larger than roughly 55 km square and says why.
    For anything bigger, prepare an extract and use
    :class:`LocalExtractOSMProvider`.

    It earns its place for the case the local path cannot cover: an operator
    asking about a corridor that was mapped after our extract was cut.
    """

    implementation: ClassVar[str] = "overpass"
    source_name: ClassVar[str] = "overpass-api"
    #: Roughly 0.5° x 0.5°, about 55 km square at this latitude.
    max_area_deg2: ClassVar[float] = 0.25

    def __init__(self, base_url: str, *, timeout_seconds: float = 60.0) -> None:
        self._base_url = base_url.rstrip("/")
        self._timeout = timeout_seconds
        self._client: Any = None

    def _http(self) -> Any:
        """Build the HTTP client on first use.

        Imported here, not at module scope, so this module stays importable — and
        the tag-parsing functions above stay unit-testable — with no HTTP library
        installed.
        """

        if self._client is None:
            import httpx

            self._client = httpx.AsyncClient(
                timeout=self._timeout,
                headers={"User-Agent": "ner-logistics/0.1 (SIH prototype)"},
            )
        return self._client

    async def aclose(self) -> None:
        if self._client is not None:
            await self._client.aclose()
            self._client = None

    @staticmethod
    def _query(bbox: Tuple[float, float, float, float], timeout: int) -> str:
        min_lon, min_lat, max_lon, max_lat = bbox
        pattern = "|".join(ROUTABLE_HIGHWAY_VALUES)
        # Overpass bbox order is (south, west, north, east) — the opposite
        # convention to GeoJSON, which is exactly the kind of flip worth doing
        # in one place with the arguments named.
        return (
            f"[out:json][timeout:{timeout}];\n"
            f'way["highway"~"^({pattern})$"]'
            f"({min_lat:.6f},{min_lon:.6f},{max_lat:.6f},{max_lon:.6f});\n"
            f"out geom tags;"
        )

    async def roads(
        self,
        *,
        bbox: Tuple[float, float, float, float],
        road_types: Optional[Iterable[RoadType]] = None,
    ) -> List[RoadFeatureRecord]:
        min_lon, min_lat, max_lon, max_lat = bbox
        area = abs(max_lon - min_lon) * abs(max_lat - min_lat)
        if area > self.max_area_deg2:
            raise ValueError(
                f"{self.name}: bounding box is {area:.2f} deg^2, above the "
                f"{self.max_area_deg2} deg^2 limit for the public Overpass API. "
                "Use a prepared extract (OSM_PROVIDER=local_extract) for bulk work."
            )

        client = self._http()
        query = self._query(bbox, int(self._timeout))
        try:
            response = await client.post(self._base_url, content=query.encode("utf-8"))
        except Exception as exc:  # httpx is not importable at module scope
            raise ProviderUnavailable(f"{self.name}: {exc}") from exc
        if response.status_code == 429:
            raise ProviderUnavailable(
                f"{self.name}: rate limited by the public Overpass API (429)"
            )
        if response.status_code >= 400:
            raise ProviderResponseError(
                f"{self.name}: HTTP {response.status_code} from Overpass"
            )
        try:
            payload = response.json()
        except ValueError as exc:
            raise ProviderResponseError(f"{self.name}: non-JSON response") from exc
        elements = payload.get("elements")
        if not isinstance(elements, list):
            raise ProviderResponseError(f"{self.name}: response has no 'elements'")

        wanted = tuple(road_types) if road_types is not None else None
        observed_at = datetime.now(timezone.utc)
        out: List[RoadFeatureRecord] = []
        for element in elements:
            if not isinstance(element, dict) or element.get("type") != "way":
                continue
            points = element.get("geometry")
            if not isinstance(points, list) or len(points) < 2:
                continue
            coordinates = [
                [float(p["lon"]), float(p["lat"])]
                for p in points
                if isinstance(p, dict) and "lat" in p and "lon" in p
            ]
            if len(coordinates) < 2:
                continue
            tags = element.get("tags")
            tags = {str(k): str(v) for k, v in tags.items()} if isinstance(tags, dict) else {}
            record = _record_from_tags(
                way_id=element.get("id") if isinstance(element.get("id"), int) else None,
                geometry={"type": "LineString", "coordinates": coordinates},
                tags=tags,
                provenance=self.provenance,
                source=self.source_name,
                observed_at=observed_at,
            )
            if wanted is not None and record.road_type not in wanted:
                continue
            out.append(record)
        return out

    async def healthcheck(self) -> ProviderStatus:
        """Reports configuration without querying.

        A readiness probe that fires an Overpass query every few seconds is how a
        deployment gets itself banned from a shared service.
        """

        return self.describe(healthy=True, detail=f"endpoint {self._base_url}, not probed")
